-- KeyComp WCL Mythic+ data HEADER (auto-generated by tools/wcl_build.py)
-- DO NOT EDIT BY HAND. Source: Warcraft Logs API v2, zone 47 (Midnight S1).
-- generated=1780824319  unique_chars=43435  rows=90399  shards=24
-- Data is sharded across WCLData01..24.lua so each Lua chunk stays
-- under the 5.1 compiler's ~262k-constants-per-function ceiling.
local _, ns = ...
KeyCompWCL = KeyCompWCL or { chars = {} }
KeyCompWCL.generated = 1780824319
KeyCompWCL.season = "Midnight S1"
KeyCompWCL.zone = 47
KeyCompWCL.chars = KeyCompWCL.chars or {}
if ns then ns.WCLData = KeyCompWCL end
